USE EDUCATION;

SELECT SUBSTRING(FNAME, 1, 1) + '.' + SURNAME + ';' + 'местожительства-' + CITY + ';' + 'родился' + BIRTHDAY AS 'SVEDENIYA'
	FROM STUDENT
	WHERE CITY IS NOT NULL AND
	BIRTHDAY IS NOT NULL;
