USE EDUCATION;

-------------------
SELECT *
	FROM EXAM_MARKS
	WHERE STUDENT_ID = (SELECT STUDENT_ID
							FROM STUDENT 
							where SURNAME='Зайцева' and fname='Ольга');

-------------------
SELECT *
	FROM EXAM_MARKS 
	WHERE STUDENT_ID IN 
		(SELECT STUDENT_ID
			FROM STUDENT
			WHERE CITY = 'Воронеж');

-------------------
SELECT COUNT(DISTINCT STUDENT_ID), avg(MARK)
	FROM EXAM_MARKS
	GROUP BY MARK
	HAVING MARK > (SELECT AVG(MARK)
						FROM EXAM_MARKS
						WHERE STUDENT_ID = 12)

--------------------
SELECT * 
	FROM SUBJECT SU
	WHERE '23/01/2000' IN (SELECT EXAM_DATE
								FROM EXAM_MARKS  EX
								WHERE  SU.SUBJ_ID = EX . SUBJ_ID);

--------------------
SELECT DISTINCT A.SUBJ_ID, SUBJ_NAME, KHOUR, SEMESTR 
	FROM SUBJECT A, EXAM_MARKS B
	WHERE  A.SUBJ_ID=B.SUBJ_ID AND  B.EXAM_DATE='23/01/2000';

-------------------
SELECT DISTINCT STUDENT_ID, SURNAME, STIPEND
	FROM STUDENT El
	WHERE STIPEND > (SELECT AVG(STIPEND) FROM STUDENT E2 WHERE El.KURS = E2.KURS)

-------------------
SELECT DISTINCT STUDENT_ID, SURNAME, STIPEND
	FROM STUDENT El, (SELECT KURS, AVG (STIPEND) AS AVG_STIPEND
							FROM STUDENT E2
							GROUP BY E2.KURS) E3
	WHERE El.STIPEND > AVG_STIPEND AND El.KURS=E3.KURS

--------------
SELECT EXAM_DATE, SUM(MARK)
	FROM EXAM_MARKS A
	GROUP BY EXAM_DATE
	HAVING 1 < (SELECT COUNT(MARK)
					FROM EXAM_MARKS В
					WHERE A.EXAM_DATE = В.EXAM_DATE)



