USE EDUCATION;

-- 1 --
SELECT MARK
	FROM EXAM_MARKS
	WHERE STUDENT_ID = (SELECT STUDENT_ID 
							FROM STUDENT
							WHERE SURNAME = 'Иванов');

--2 --
SELECT FNAME
	FROM STUDENT
	WHERE STUDENT_ID IN (SELECT STUDENT_ID
							FROM EXAM_MARKS
								WHERE SUBJ_ID = 22 AND MARK > (SELECT CONVERT(DECIMAL(3, 1), AVG(CONVERT(DECIMAL(3, 1), MARK))) 
																	FROM EXAM_MARKS));

-- 3 --
SELECT FNAME
	FROM STUDENT
	WHERE STUDENT_ID IN (SELECT STUDENT_ID
							FROM EXAM_MARKS
							WHERE SUBJ_ID = 22 AND MARK < (SELECT CONVERT(DECIMAL(3, 1), AVG(CONVERT(DECIMAL(3, 1), MARK)))
																FROM EXAM_MARKS));

-- 4 --
SELECT COUNT (SUBJ_ID) [количество предметов]
	FROM EXAM_MARKS OUTSIDE
	GROUP BY STUDENT_ID
	HAVING 2 < (SELECT COUNT (SUBJ_ID) FROM EXAM_MARKS INSIDE WHERE INSIDE.STUDENT_ID = OUTSIDE.STUDENT_ID AND MARK > 2);

-- 5 --
SELECT STUDENT_ID, FNAME
	FROM STUDENT OUTSIDE
	WHERE STIPEND = (SELECT MAX(STIPEND) FROM STUDENT INSIDE WHERE OUTSIDE.CITY = INSIDE.CITY AND STIPEND > 0);

-- 6 --
SELECT STUDENT_ID, FNAME
	FROM STUDENT OUTSIDE
	WHERE NOT EXISTS (SELECT CITY FROM UNIVERSITY INSIDE WHERE OUTSIDE.CITY = INSIDE.CITY)

