USE EDUCATION;

-- 1 --
SELECT COUNT(STUDENT_ID)
	FROM EXAM_MARKS
	WHERE SUBJ_ID = 22 AND MARK >= 4;

-- 2 --
SELECT COUNT(DISTINCT SUBJ_ID)
	FROM EXAM_MARKS;

-- 3 --
SELECT STUDENT_ID, MIN(MARK)
	FROM EXAM_MARKS
	GROUP BY STUDENT_ID;

-- 4 --
SELECT STUDENT_ID, MAX(MARK)
	FROM EXAM_MARKS
	GROUP BY STUDENT_ID;

-- 5 --
SELECT TOP 1 SURNAME
	FROM STUDENT
	WHERE SURNAME LIKE 'È%'
	ORDER BY SURNAME;

-- 6 --
SELECT SUBJ_NAME, MAX(SEMESTR)
	FROM SUBJECT
	GROUP BY SUBJ_NAME;

-- 7 --
SELECT EXAM_DATE, COUNT(STUDENT_ID)
	FROM EXAM_MARKS
	WHERE MARK > 2
	GROUP BY EXAM_DATE;

-- 8 --
SELECT '1', SUBJ_ID, AVG(MARK)
	FROM EXAM_MARKS
	WHERE SUBJ_ID IN
		(SELECT SUBJ_ID
			FROM SUBJECT
			WHERE SEMESTR IN(1 , 2))
	GROUP BY SUBJ_ID
UNION 
SELECT '2', SUBJ_ID, AVG(MARK)
	FROM EXAM_MARKS
	WHERE SUBJ_ID IN
		(SELECT SUBJ_ID
			FROM SUBJECT
			WHERE SEMESTR IN(3 , 4))
	GROUP BY SUBJ_ID

UNION
 
SELECT '3', SUBJ_ID, AVG(MARK)
	FROM EXAM_MARKS
	WHERE SUBJ_ID IN
		(SELECT SUBJ_ID FROM SUBJECT WHERE SEMESTR IN(5 , 6)) GROUP BY SUBJ_ID

UNION
 
SELECT '4', SUBJ_ID, AVG(MARK)
	FROM EXAM_MARKS
	WHERE SUBJ_ID IN
		(SELECT SUBJ_ID FROM SUBJECT WHERE SEMESTR IN(7 , 8))
	GROUP BY SUBJ_ID

UNION

SELECT '5', SUBJ_ID, AVG(MARK)
	FROM EXAM_MARKS
	WHERE SUBJ_ID IN
		(SELECT SUBJ_ID FROM SUBJECT WHERE SEMESTR IN(9 , 10))
	GROUP BY SUBJ_ID;

-- 9 --

SELECT STUDENT_ID, CONVERT(DECIMAL(3,1), AVG(CONVERT(DECIMAL(3,1), MARK)))
	FROM EXAM_MARKS
	GROUP BY STUDENT_ID;

-- 10 --
SELECT EXAM_ID, CONVERT(DECIMAL(3, 1), AVG(CONVERT(DECIMAL(3, 1), MARK)))
	FROM EXAM_MARKS
	WHERE MARK IS NOT NULL
	GROUP BY EXAM_ID;

-- 11 --
SELECT SUBJ_ID, COUNT(STUDENT_ID)
	FROM EXAM_MARKS
	GROUP BY SUBJ_ID;

-- 12 --
SELECT '1', COUNT(DISTINCT SUBJ_ID)
	FROM SUBJECT
	WHERE SEMESTR IN (1, 2)

UNION

SELECT '2', COUNT(DISTINCT SUBJ_ID)
	FROM SUBJECT
	WHERE SEMESTR IN (3, 4)

UNION

SELECT '3', COUNT(DISTINCT SUBJ_ID)
	FROM SUBJECT
	WHERE SEMESTR IN (5, 6)

UNION

SELECT '4', COUNT(DISTINCT SUBJ_ID)
	FROM SUBJECT
	WHERE SEMESTR IN (7, 8)

UNION

SELECT '5', COUNT(DISTINCT SUBJ_ID)
	FROM SUBJECT
	WHERE SEMESTR IN (9, 10);

-- 13 --
SELECT STUDENT_ID, SURNAME, 1.2 * STIPEND
	FROM STUDENT
	WHERE STIPEND > 0
	ORDER BY STIPEND DESC;

SELECT STUDENT_ID, SURNAME, 1.2 * STIPEND
	FROM STUDENT
	WHERE STIPEND > 0
	ORDER BY SURNAME;